[package]
name = "adb-write-date"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adb = { path = "../adb" }
clap = "2.33"
